name: Wipe Repository

on:
  workflow_dispatch: # Run manually from GitHub Actions tab

jobs:
  wipe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (with full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Important! Brings .git folder

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Wipe repository (except .git and workflows)
        run: |
          # Delete everything except .git and .github/workflows
          find . -mindepth 1 \
            -not -path "./.git*" \
            -not -path "./.github/workflows*" \
            -exec rm -rf {} +
          
          # Add a clean README
          echo "# Clean Repository" > README.md
          git add -A
          git commit -m "Wipe repository clean"

      - name: Force push clean state
        run: |
          git branch -M main
          git push origin main --force
